---
- name: Ensure ssl save paths exist
  no_log: true
  file:
    path: '{{ munin_nginx_ssl_save_path }}'
    state: directory
    owner: root
    group: www-data
    mode: '0440'
  when: munin_nginx_ssl_save_path is defined

- name: Generate trustchain.crt
  no_log: true
  template:
    src: 'ssl/trustchain.crt'
    dest: '{{ munin_nginx_ssl_trusted_certificate_path }}'
  when: munin_nginx_ssl_root_certificate != '' and munin_nginx_ssl_intermediate_certificate != ''

- name: Generate certificate.key
  no_log: true
  template:
    src: 'ssl/certificate.key'
    dest: '{{ munin_nginx_ssl_certificate_key_path }}'
  when: munin_nginx_ssl_certificate_key != ''

- name: Generate certificate.crt
  no_log: true
  template:
    src: 'ssl/certificate.crt'
    dest: '{{ munin_nginx_ssl_certificate_path }}'
  when: munin_nginx_ssl_certificate != '' and munin_nginx_ssl_intermediate_certificate != ''

- name: Generate dhparam file
  openssl_dhparam:
    path: '{{ munin_nginx_ssl_save_path }}/dhparam.pem'
    size: '{{ munin_dhparam_size }}'
  notify: reload nginx
  changed_when: false

- name: Ensure nginx vhost is linked
  template:
    src: 'nginx.conf'
    dest: '/etc/nginx/sites-enabled/munin-node.conf'
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx