---
- name: Ensure nginx vhost is linked
  template:
    src: 'nginx.conf'
    dest: '/etc/nginx/sites-enabled/munin-node.conf'
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx